
name: develop Merge master
on:
  # 推送代码后触发
  push:
    branches:
      - master
  # 定时任务触发，使用 cron 规则，这里默认一小时执行一次
  #   schedule:
  #     - cron: '0 * * * *'
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge origin master
        run: |
          git config --global user.name 'Autumn'
          git config --global user.email '439661734@qq.com'
          git pull --unshallow
          # 设置上游仓库
          # git remote add upstream https://github.com/upstream/upstream.git
          # git fetch upstream
          git checkout -b develop origin/develop
          git merge --no-edit origin/master
          git push origin develop